services:
  - type: web
    name: keysmith
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn keysmith.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: keysmith.settings
      - key: SECRET_KEY
        value: your-secret-key-here
      - key: DEBUG
        value: "False"
